<a href="https://colab.research.google.com/github/Fatimhprog/AI-Generated-Text-Detection-MSIS822/blob/main/data/code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from datasets import load_dataset

dataset = load_dataset("KFUPM-JRCAI/arabic-generated-abstracts")

README.md:   0%|          | 0.00/8.10k [00:00<?, ?B/s]

data/by_polishing-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 8.49MB

data/by_polishing-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/from_title-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 6.90MB

data/from_title-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/from_title_and_content-00000-of-000(…): reconstructing file:   0%|          |  0.00B / 7.01MB

data/from_title_and_content-00000-of-000(…): downloading bytes:           |  0.00B

Generating by_polishing split:   0%|          | 0/2851 [00:00<?, ? examples/s]

Generating from_title split:   0%|          | 0/2963 [00:00<?, ? examples/s]

Generating from_title_and_content split:   0%|          | 0/2574 [00:00<?, ? examples/s]

In [ ]:

df = dataset["by_polishing"].to_pandas()

print(df.columns)
print(df.dtypes)
df.head()

Index(['original_abstract', 'allam_generated_abstract',
       'jais_generated_abstract', 'llama_generated_abstract',
       'openai_generated_abstract'],
      dtype='object')
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يتناول هذا البحث موضوع التعليم بين النساء الأن...,تدرس هذه الدراسة دور المرأة في التعليم في الأن...,يُقدم هذا البحث دراسة شاملة حول حالة التعليم ع...,صور نظام التعليم عند المرأة الأندلسية تستند إل...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,يتناول هذا البحث دراسة انهيار دولة الموحدين من...,كان العامل الثقافي من بين الأسباب الرئيسية الت...,يعد العامل الثقافي أحد أبرز الأسباب التي يعزى ...,انهيار دولة الموحدين يعود بشكل كبير للعوامل ال...
2,شكلت تلك الجهود والمساعي الرائدة التي قام بها ...,هدفت هذه الدراسة إلى تسليط الضوء على جهود قادة...,تدرس هذه الدراسة جهود قادة الثورة الجزائرية خل...,شكلت الجهود التي بذلها قادة الثورة الجزائرية خ...,جهود قادة الثورة الجزائرية خلال المرحلة الأولى...
3,يقوم المقال على اشكالية الضرائب الغير شرعية في...,يتناول هذا البحث إشكالية الضرائب غير الشرعية ف...,تدرس المقالة مشكلة الضرائب غير الشرعية في مراح...,يقوم البحث على دراسة الضرائب غير الشرعية في دو...,المقال يناقش قضية الضرائب غير الشرعية في دولتي...
4,تتفق المصادر التاريخية المتوفرة حول موضوع تطور...,تتناول هذه الدراسة حركة الانتصار للحريات الديم...,حركة انتصار الحريات الديمقراطية (MTLD)، وهي حر...,تُظهر المصادر التاريخية المتاحة حول تطور الحرك...,حركة انتصار الحريات الديمقراطية (MTLD) في الجز...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = dataset["by_polishing"].to_pandas()

human_rows = [{"text": row["original_abstract"], "label": "human"}
              for _, row in df.iterrows()]

ai_rows = []
for _, row in df.iterrows():
    ai_rows.append({"text": row["allam_generated_abstract"], "label": "ai_generated"})
    ai_rows.append({"text": row["jais_generated_abstract"], "label": "ai_generated"})
    ai_rows.append({"text": row["llama_generated_abstract"], "label": "ai_generated"})
    ai_rows.append({"text": row["openai_generated_abstract"], "label": "ai_generated"})

df_labels = pd.DataFrame(human_rows + ai_rows)

In [ ]:
df_labels["label"].value_counts()

label
ai_generated    11404
human            2851
Name: count, dtype: int64

In [ ]:
df_labels.isnull().sum()

text     0
label    0
dtype: int64

In [ ]:
df_labels[df_labels.duplicated()]

Empty DataFrame
Columns: [text, label]
Index: []

In [ ]:
df_labels.duplicated().sum()

np.int64(0)

In [ ]:
df_labels["label"].value_counts()

label
ai_generated    11404
human            2851
Name: count, dtype: int64